/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_crypto_plus_provider_ock_NativeOCKImplementation */

#ifndef _Included_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
#define _Included_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ockDynamicallyLoaded
#define com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ockDynamicallyLoaded 1L
/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    getLibraryBuildDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_getLibraryBuildDate
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    initializeOCK
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_initializeOCK
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CTX_getValue
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CTX_1getValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    getByteBufferPointer
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_getByteBufferPointer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RAND_nextBytes
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RAND_1nextBytes
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RAND_setSeed
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RAND_1setSeed
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RAND_generateSeed
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RAND_1generateSeed
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    EXTRAND_create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_EXTRAND_1create
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    EXTRAND_nextBytes
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_EXTRAND_1nextBytes
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    EXTRAND_setSeed
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_EXTRAND_1setSeed
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    EXTRAND_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_EXTRAND_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1create
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_init
 * Signature: (JJII[B[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1init
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_clean
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1clean
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_setPadding
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1setPadding
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_getBlockSize
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1getBlockSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_getKeyLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1getKeyLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_getIVLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1getIVLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_getOID
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1getOID
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_encryptUpdate
 * Signature: (JJ[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1encryptUpdate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_decryptUpdate
 * Signature: (JJ[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1decryptUpdate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_encryptFinal
 * Signature: (JJ[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1encryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_decryptFinal
 * Signature: (JJ[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1decryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    checkHardwareSupport
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_checkHardwareSupport
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    CIPHER_KeyWraporUnwrap
 * Signature: (J[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_CIPHER_1KeyWraporUnwrap
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    z_kmc_native
 * Signature: ([BI[BIJII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_z_1kmc_1native
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jlong, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1create
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_init
 * Signature: (JJI[B[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1init
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_clean
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1clean
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_setPadding
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1setPadding
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_getBlockSize
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1getBlockSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_getKeyLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1getKeyLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_getIVLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1getIVLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_getOID
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1getOID
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_encryptUpdate
 * Signature: (JJ[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1encryptUpdate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_decryptUpdate
 * Signature: (JJ[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1decryptUpdate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_encryptFinal
 * Signature: (JJ[BII[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1encryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_decryptFinal
 * Signature: (JJ[BII[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1decryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    POLY1305CIPHER_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_POLY1305CIPHER_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_checkHardwareGCMSupport
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1checkHardwareGCMSupport
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_encryptFastJNI_WithHardwareSupport
 * Signature: (IIIIIIIJ[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1encryptFastJNI_1WithHardwareSupport
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_encryptFastJNI
 * Signature: (JJIIIIIIIJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1encryptFastJNI
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_decryptFastJNI_WithHardwareSupport
 * Signature: (IIIIIIIJ[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1decryptFastJNI_1WithHardwareSupport
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_decryptFastJNI
 * Signature: (JJIIIIIIIJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1decryptFastJNI
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_encrypt
 * Signature: (JJ[BI[BI[BII[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1encrypt
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_decrypt
 * Signature: (JJ[BI[BI[BII[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1decrypt
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_FinalForUpdateEncrypt
 * Signature: (JJ[BI[BI[BII[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1FinalForUpdateEncrypt
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_FinalForUpdateDecrypt
 * Signature: (JJ[BII[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1FinalForUpdateDecrypt
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_UpdForUpdateEncrypt
 * Signature: (JJ[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1UpdForUpdateEncrypt
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_UpdForUpdateDecrypt
 * Signature: (JJ[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1UpdForUpdateDecrypt
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_InitForUpdateEncrypt
 * Signature: (JJ[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1InitForUpdateEncrypt
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_InitForUpdateDecrypt
 * Signature: (JJ[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1InitForUpdateDecrypt
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_GCM_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1GCM_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    free_GCM_ctx
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_free_1GCM_1ctx
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    create_GCM_context
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_create_1GCM_1context
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_CCM_checkHardwareCCMSupport
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1CCM_1checkHardwareCCMSupport
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_CCM_encryptFastJNI_WithHardwareSupport
 * Signature: (IIIIIIIJ[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1CCM_1encryptFastJNI_1WithHardwareSupport
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_CCM_encryptFastJNI
 * Signature: (JIIIIIIJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1CCM_1encryptFastJNI
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_CCM_decryptFastJNI_WithHardwareSupport
 * Signature: (IIIIIIIJ[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1CCM_1decryptFastJNI_1WithHardwareSupport
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_CCM_decryptFastJNI
 * Signature: (JIIIIIIJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1CCM_1decryptFastJNI
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_CCM_encrypt
 * Signature: (J[BI[BI[BI[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1CCM_1encrypt
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_CCM_decrypt
 * Signature: (J[BI[BI[BI[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1CCM_1decrypt
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    do_CCM_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_do_1CCM_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSACIPHER_public_encrypt
 * Signature: (JJIII[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSACIPHER_1public_1encrypt
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSACIPHER_private_encrypt
 * Signature: (JJI[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSACIPHER_1private_1encrypt
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSACIPHER_public_decrypt
 * Signature: (JJI[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSACIPHER_1public_1decrypt
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSACIPHER_private_decrypt
 * Signature: (JJIII[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSACIPHER_1private_1decrypt
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_generate
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1generate__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_generateParameters
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1generateParameters
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_generate
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1generate__J_3B
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_createPrivateKey
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1createPrivateKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_createPublicKey
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1createPublicKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_getParameters
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1getParameters
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_getPrivateKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1getPrivateKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_getPublicKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1getPublicKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_createPKey
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1createPKey
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_computeDHSecret
 * Signature: (JJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1computeDHSecret
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DHKEY_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DHKEY_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAKEY_generate
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAKEY_1generate
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAKEY_createPrivateKey
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAKEY_1createPrivateKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAKEY_createPublicKey
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAKEY_1createPublicKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAKEY_getPrivateKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAKEY_1getPrivateKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAKEY_getPublicKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAKEY_1getPublicKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAKEY_size
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAKEY_1size
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAKEY_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAKEY_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_generate
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1generate__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_generateParameters
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1generateParameters
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_generate
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1generate__J_3B
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_createPrivateKey
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1createPrivateKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_createPublicKey
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1createPublicKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_getParameters
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1getParameters
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_getPrivateKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1getPrivateKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_getPublicKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1getPublicKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_createPKey
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1createPKey
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSAKEY_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSAKEY_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    PKEY_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_PKEY_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1create
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_copy
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1copy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_update
 * Signature: (JJ[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1update
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_updateFastJNI
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1updateFastJNI
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_digest
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1digest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_digest_and_reset
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1digest_1and_1reset__JJJI
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_digest_and_reset
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1digest_1and_1reset__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_size
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1size
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_reset
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1reset
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DIGEST_PKCS12KeyDeriveHelp
 * Signature: (JJ[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DIGEST_1PKCS12KeyDeriveHelp
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    SIGNATURE_sign
 * Signature: (JJJZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_SIGNATURE_1sign
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    SIGNATURE_verify
 * Signature: (JJJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_SIGNATURE_1verify
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    SIGNATUREEdDSA_signOneShot
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_SIGNATUREEdDSA_1signOneShot
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    SIGNATUREEdDSA_verifyOneShot
 * Signature: (JJ[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_SIGNATUREEdDSA_1verifyOneShot
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_signInit
 * Signature: (JJJIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1signInit
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_verifyInit
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1verifyInit
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_getSigLen
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1getSigLen
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_signFinal
 * Signature: (JJ[BI)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1signFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_verifyFinal
 * Signature: (JJ[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1verifyFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_createContext
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1createContext
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_releaseContext
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1releaseContext
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_digestUpdate
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1digestUpdate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_reset
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1reset
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSAPSS_resetDigest
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSAPSS_1resetDigest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSANONE_SIGNATURE_sign
 * Signature: (J[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSANONE_1SIGNATURE_1sign
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    DSANONE_SIGNATURE_verify
 * Signature: (J[BJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_DSANONE_1SIGNATURE_1verify
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSASSL_SIGNATURE_sign
 * Signature: (J[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSASSL_1SIGNATURE_1sign
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    RSASSL_SIGNATURE_verify
 * Signature: (J[BJ[BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_RSASSL_1SIGNATURE_1verify
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jbyteArray, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HMAC_create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HMAC_1create
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HMAC_update
 * Signature: (JJ[BI[BIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HMAC_1update
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jbyteArray, jint, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HMAC_doFinal
 * Signature: (JJ[BI[BZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HMAC_1doFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jbyteArray, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HMAC_size
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HMAC_1size
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HMAC_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HMAC_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_generate
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1generate__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_generate
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1generate__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XECKEY_generate
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XECKEY_1generate
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_generateParameters
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1generateParameters__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_generateParameters
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1generateParameters__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_generate
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1generate__J_3B
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_createPrivateKey
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1createPrivateKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XECKEY_createPrivateKey
 * Signature: (J[BJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XECKEY_1createPrivateKey
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_createPublicKey
 * Signature: (J[B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1createPublicKey
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XECKEY_createPublicKey
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XECKEY_1createPublicKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_getParameters
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1getParameters
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_getPrivateKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1getPrivateKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XECKEY_getPrivateKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XECKEY_1getPrivateKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_getPublicKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1getPublicKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XECKEY_getPublicKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XECKEY_1getPublicKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_createPKey
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1createPKey
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XECKEY_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XECKEY_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XDHKeyAgreement_init
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XDHKeyAgreement_1init
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XDHKeyAgreement_setPeer
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XDHKeyAgreement_1setPeer
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_computeECDHSecret
 * Signature: (JJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1computeECDHSecret
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    XECKEY_computeECDHSecret
 * Signature: (JJJJI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_XECKEY_1computeECDHSecret
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_signDatawithECDSA
 * Signature: (J[BIJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1signDatawithECDSA
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    ECKEY_verifyDatawithECDSA
 * Signature: (J[BI[BIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_ECKEY_1verifyDatawithECDSA
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HKDF_create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HKDF_1create
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HKDF_extract
 * Signature: (JJ[BJ[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HKDF_1extract
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jbyteArray, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HKDF_expand
 * Signature: (JJ[BJ[BJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HKDF_1expand
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HKDF_derive
 * Signature: (JJ[BJ[BJ[BJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HKDF_1derive
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HKDF_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HKDF_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    HKDF_size
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_HKDF_1size
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    PBKDF2_derive
 * Signature: (JLjava/lang/String;[B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_PBKDF2_1derive
  (JNIEnv *, jclass, jlong, jstring, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    MLKEY_generate
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_MLKEY_1generate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    MLKEY_createPrivateKey
 * Signature: (JLjava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_MLKEY_1createPrivateKey
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    MLKEY_createPublicKey
 * Signature: (JLjava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_MLKEY_1createPublicKey
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    MLKEY_getPrivateKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_MLKEY_1getPrivateKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    MLKEY_getPublicKeyBytes
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_MLKEY_1getPublicKeyBytes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    MLKEY_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_MLKEY_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    KEM_encapsulate
 * Signature: (JJ[B[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_KEM_1encapsulate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    KEM_decapsulate
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_KEM_1decapsulate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    PQC_SIGNATURE_sign
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_PQC_1SIGNATURE_1sign
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_ock_NativeOCKImplementation
 * Method:    PQC_SIGNATURE_verify
 * Signature: (JJ[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_crypto_plus_provider_ock_NativeOCKImplementation_PQC_1SIGNATURE_1verify
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
